### PR TITLE
Use Go 1.7

### PR DESCRIPTION
**Pull request by jkakar**
Also remove unused boilerplate notification logic.

### CODE REVIEW

**Comment by cyberdelia** [comment]
@jkakar, thanks for your PR! By analyzing the annotation information on this pull request, we identified @freeformz, @voidlock and @apg to be potential reviewers

**Comment by voidlock** [comment]
👍

**Comment by freeformz** [comment]
Can we bump this to go1.7.2 when it's released later today/tomorrow?

**Comment by jkakar** [comment]
@freeformz Works for me.

**Pull request merged**
