### PR TITLE
one more tweak for pre-v15 parity

### PR DESCRIPTION
**Pull request by voidlock**
Another fix for #71. Prior to v15 log-shuttle would update `batch.fill`
anytime a batch was sent. This happened regardless of whether the batch
was full or not.

### CODE REVIEW

**Comment by freeformz** [comment]
How about passing a time.Time to deliverOrDropCurrent instead and call rdr.batchFillTime.Update there?

**Comment by voidlock** [comment]
Good point, but passed a duration instead.

**Comment by freeformz** [comment]
Yeah, good call. :+1:
I really should refactor the reader. looks a mess now.

**Comment by rsampaio** [comment]
:+1:

**Pull request merged**
