### PR TITLE
Add the ability to gzip http payloads

### PR DESCRIPTION
**Pull request by collinvandyck**
This is done with a `GzipFormatter` that composes an `HTTPFormatter`.

### CODE REVIEW

**Comment by freeformz** [comment]
Thanks @collinvandyck for taking the time to do this!

After reading the code I can think of 2 main issues:
1) This implementation requires reading all the formatted, gzipped bytes into []byte. I'd much rather chain interfaces together using an io.Pipe connecting the gzip writer to the eventual reader. This has the advantage of only moving bytes as needed, when needed and in smaller chunks without having to make a larger internal buffer (that is also duplicated by the caller of Read()).

2) Please move the decision to use the gzipFormatter out of the logplex formatter and into the http client.

FWIW: I am likely to remove ContentLength from the interface as Logplex now supports chunked encoding. Previously it did not and that is the only reason ContentLength is part of the interface.

Thoughts?

**Comment by collinvandyck** [comment]
The main reason I did not use io.Pipe() is because of the ContentLength() interface method.  If I chain together the gzip writer to the reader, I will not know the compressed content length.   Does that make sense?

Also, I'm happy to remove ContentLength as a part of this PR, and then chain together the readers/writers as you suggested. How does that sound?

**Comment by freeformz** [comment]
@collinvandyck I would rather separate the 2.

For now you could just implement ContentLength() returning 0 and not set it as part of Request()

**Comment by collinvandyck** [comment]
@freeformz I believe that should do it, let me know :)

**Comment by collinvandyck** [comment]
Sorry, I forgot about 2 above (moving creating gzip formatter to the http client), will change that

**Comment by collinvandyck** [comment]
Ok, moved the gzip formatter creation to the http outlet. I had to set ContentLength on the request to override the ContentLength that the delegate set.

**Comment by freeformz** [comment]
@collinvandyck With tests!. Merged.

**Pull request merged**
