### PR TITLE
Switch to pborman/uuid library

### PR DESCRIPTION
**Pull request by freeformz**
/cc @dpiddy

### CODE REVIEW

**Comment by apg** [comment]
What is the reasoning for the switch?

**Comment by freeformz** [comment]
1. It's a more popular UUID library.
1. It's the library used most widely internally as well.
1. Dogwood uses it.

Net sum it's likely to reduce other people's dependencies if they also use UUIDs.

**Comment by dpiddy** [comment]
:+1:

**Comment by apg** [comment]
:+1:

**Pull request merged**
