### PR TITLE
add Dockerfile for packaging

### PR DESCRIPTION
**Pull request by ddollar**

### CODE REVIEW

**Comment by freeformz** [comment]
Thanks, I've been wondering how log-shuttle exists in a docker world...

I am not sure I'm going to accept this though because:

1. I don't really understand the use case for a log-shuttle Dockerfile. Seems like something you would install in your own docker container if you wanted to use it. But I'm probably being short sighted/ignorant.
1. The results are *huge*. When cross compiled log-shuttle doesn't really need much of anything except maybe some root CA stuff. But I'm not sure how to put all of that together in the docker ecosystem in as clean a way as this Dockerfile.

Your thoughts on the above are most welcome.

**Comment by ddollar** [comment]
1. This is handy to give you log-shuttle anywhere you have Docker, for example:

`docker run ddollar/log-shuttle -front-buff 300 ...`

2. If you build it raw the image is huge because it has Go in there for the build. If you'll notice the Dockerfile deletes Go after it is done. This doesn't help by itself since Docker images are combinations of layers but if you pass it through something like [docker-squash](https://github.com/jwilder/docker-squash) it flattens out quite nicely. See my images list below:

```
$ docker images | grep shuttle
ddollar/shuttle   release              d720cfcba251        22 hours ago        17.04 MB
ddollar/shuttle   latest               7c1c11921df7        22 hours ago        118 MB
```

**Comment by freeformz** [comment]
Re 1:
But why not just run `tail -qF -n 0 /var/log/app.log | log-shuttle -front-buff 300 ...`? Is it because we haven't really published packages?

Re 2:
That's still huge, when it could be like ~5-10MB. Although as a first pass I guess it's not so bad if it's squashed. We can always optimize more in the future.

**Comment by ddollar** [comment]
As far as how log-shuttle exists in the wider Docker world: I wouldn't put it inside your containers. Probably something like this:

`docker run myapp | docker run shuttle -logs-url ...`

**Comment by freeformz** [comment]
Thanks. I'll merge for now and add a note to publish a heroku/log-shuttle when I next do a release.

**Comment by ddollar** [comment]
Thanks!

**Comment by ddollar** [comment]
If you want to squash it before releasing, you can use my Dockerized docker-squash `ddollar/squash` based on https://github.com/ddollar/docker-squash/tree/dockerize.

Use it like this:

```
docker build -t heroku/log-shuttle
docker save heroku/log-shuttle | docker run -i ddollar/squash -verbose -t heroku/log-shuttle:release | docker load
```

**Pull request merged**
